Add option for brim ears in the corners
kennetek/gridfinity-rebuilt-openscad pull request #121
Opened 2023-07-04 20:39 UTC by haeky

Add an option to add brim ears in the corners to help with warping/lifting. 

This helps when printing larger boxes.

(This is my first time writing in OpenSCAD, feel free to comment on the code or structure).

2023-07-09 08:32 UTC, Ruudjhuu commented
Nice idea. I do think this feature should be supported by slicers, but most slicers do not yet support it so lets proceed with this. 

The circle you created overlaps with the magnet/screw holes.This can be eliminated by cutting away the overlapping part.

I would also like to see the size and height to also be adjustable from the customizer window. (I prefer a list which contains all brim settings being passed through as arguments in the functions.

Could you also add this feature to the `lite-bins` , `base-plate` and if possible `spiral-vase`?

For the rest, it does look good.

2023-07-09 08:37 UTC, Ruudjhuu requested changes

2023-07-09 08:37 UTC, Ruudjhuu commented on gridfinity-rebuilt-utility.scad
> +    copy_mirror()
```suggestion
    pattern_circular(4)
```

2024-01-15 18:47 UTC, closed without merging

2024-11-20 22:47 UTC, hcooper commented
Hey - was any further progress made with this? I'd be interested in making it work, as slicer brim options don't work perfectly for me.