Fix Baseplate Not Rendering & Generate Baseplate From Profile
kennetek/gridfinity-rebuilt-openscad pull request #187
Opened 2024-05-17 13:42 UTC by EmperorArthur

Incorporates #179

# Main Changes

First, this fixes the baseplate not correctly in [OpenSCAD](https://www.openscad.org/) version 2024.02.16 (git 55be9cf86).  Done by switching from `minovsky` to `offset` in one function.

Second, instead of using a negative of the bin's this creates the base plate using technical data from [the spec](https://gridfinity.xyz/specification/).

# Other changes

Deprecated `rounded_rectangle` in favor of a new `rounded_square` function.  Which operates like the built in `square` and `cube` functions.

## Opinion

The `minovsky` function just seems to cause more issues than it is worth.

2024-05-17 13:46 UTC, EmperorArthur commented
Pictures from `python -m unittest`
![only_counterbored_screw_holes_top](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/42b43089-b89d-4624-96dd-abc4430332d2)
![only_countersunk_screw_holes_bottom](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/9a206e71-6557-497c-9b74-0d41e5ba157e)
![only_countersunk_screw_holes_top](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/99dcfd01-4410-4409-a003-97ad79ecac67)
![plain_magnet_holes_top](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/3b44ebe2-fa5c-4d86-b894-f6f4bfe2cb0a)
![ribbed_magnet_holes](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/b8d39982-bc0c-4cc6-9c79-19d96947cea3)
![chamfered_and_ribbed_magnet_holes](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/d7e87003-f601-4d43-b4e5-4eb8ebc691f1)
![chamfered_magnet_holes](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/187964d3-649e-4e4e-ba10-d96da6ab69fb)
![magnet_and_counterbored_screw_holes_bottom](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/1b566849-a607-437f-9882-75f045fceb2e)
![magnet_and_counterbored_screw_holes_top](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/2590410b-44cb-4c75-8c87-6b5750b5778c)
![magnet_and_countersunk_screw_holes_bottom](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/5cddd326-469b-47aa-b173-746b9857cb03)
![magnet_and_countersunk_screw_holes_top](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/9a874f3e-fedd-44ce-b009-f74131c4e1b5)
![magnet_holes_bottom](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/7c6f0b9b-58ea-44c3-a739-7e424a32c26f)
![no_holes_bottom](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/9d888cd6-49cb-4cd8-a4ff-ab6f9bc5eae6)
![no_holes_top](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/88ff4140-d0b5-48dc-8e28-ab5b018c7bae)
![only_counterbored_screw_holes_bottom](https://github.com/kennetek/gridfinity-rebuilt-openscad/assets/1515637/d5992c79-440b-4b71-837b-37a23b57aae1)

2024-05-27 19:40 UTC, nirvdrum commented
I tried out this PR for my first Gridfinity baseplate. It worked great. I quite like the crush ribs for keeping magnets in place. Thanks for pulling this together.

2024-06-14 14:42 UTC, ndemarco requested changes
Fit to drawer functionality has been lost.

The PR uses more modular construction (square_baseplate_lip, solid_square_baseplate, square_baseplate_corner), which appears to focus more on the modular and customizable aspect rather than ensuring the "fit to drawer" functionality.

2024-06-15 19:02 UTC, EmperorArthur commented
> Fit to drawer functionality has been lost.
> 
> The PR uses more modular construction (square_baseplate_lip, solid_square_baseplate, square_baseplate_corner), which appears to focus more on the modular and customizable aspect rather than ensuring the "fit to drawer" functionality.

Fit to drawer functionality has been restored, though tests were not added.

Please re-examine.

2024-06-20 14:38 UTC, ndemarco reviewed
Works as intended. Excellent updates.

2024-06-26 19:28 UTC, EmperorArthur commented
> Works as intended. Excellent updates.

Thanks!  It won't let me merge until you approve the re-review. :/

2024-07-14 06:22 UTC, freiser77 commented
@EmperorArthur : Thanks for your bugfix. I'm using your branch as a second remote origin and it solves #202  perfectly for me.

2024-07-28 23:04 UTC, EmperorArthur commented
Tried manually merging this, but "main" is a protected branch, and requires one reviewer to approve.

2024-07-31 13:17 UTC, ndemarco commented
Works as intended.

`Baseplates with `style` skeletonized and `style_hole` none is thicker than the same style with counterbore or countersink. The additional thickness when no screw holes are in place is unnecessary.

2024-07-31 16:58 UTC, ndemarco approved these changes

2024-07-31 16:58 UTC, ndemarco commented on tests/openscad_runner.py
Nice.

2024-08-08 10:47 UTC, Ruudjhuu approved these changes

2024-08-09 04:48 UTC, merged